//SignUp
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILED = "SIGNUP_FAILED";
//SignUp
export const SIGNOUT_REQUEST = "SIGNOUT_REQUEST";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_FAILED = "SIGNOUT_FAILED";
//SignUp
export const ACTIVE_ACCOUNT_REQUEST = "ACTIVE_ACCOUNT_REQUEST";
export const ACTIVE_ACCOUNT_SUCCESS = "ACTIVE_ACCOUNT_SUCCESS";
export const ACTIVE_ACCOUNT_FAILURE = "ACTIVE_ACCOUNT_FAILURE";
//Signin
export const SIGNIN_REQUEST = "SIGNIN_REQUEST";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILED = "SIGNIN_FAILED";
//getProductsByCategories
export const GET_PRODUCTS_BY_CATEGORIES_REQUEST =
  "GET_PRODUCTS_BY_CATEGORIES_REQUEST";
export const GET_PRODUCTS_BY_CATEGORIES_SUCCESS =
  "GET_PRODUCTS_BY_CATEGORIES_SUCCESS";
export const GET_PRODUCTS_BY_CATEGORIES_FAILURE =
  "GET_PRODUCTS_BY_CATEGORIES_FAILURE";
//getProductsByCategories
export const GET_PRODUCTS_COLOR_REQUEST = "GET_PRODUCTS_COLOR_REQUEST";
export const GET_PRODUCTS_COLOR_SUCCESS = "GET_PRODUCTS_COLOR_SUCCESS";
export const GET_PRODUCTS_COLOR_FAILURE = "GET_PRODUCTS_COLOR_FAILURE";
//getCategories
export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";
//deletUser
export const DELETE_USER_REQUEST = "Delete_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";
//getAllEmail
export const GET_ALL_EMAIL_REQUEST = "GET_ALL_EMAIL_REQUEST";
export const GET_ALL_EMAIL_SUCCESS = "GET_ALL_EMAIL_SUCCESS";
export const GET_ALL_EMAIL_FAILURE = "GET_ALL_EMAIL_FAILURE";
//getSingleProduct
export const GET_SINGLE_PRODUCT_REQUEST = "GET_SINGLE_PRODUCT_REQUEST";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCT_FAILURE = "GET_SINGLE_PRODUCT_FAILURE";
